### ISSUE TITLE
Train VirFinder with new geomes

### ISSUE THREAD

**Issue by alyosama** [jessieren/VirFinder#10]
Hi @jessieren 

I tried to train VirFinder with new genomes but it shows me this error. 

`
Error in save(seqTrainKmerCount, file = file.path(seqTrainKmerCountDir,  :
  error writing to connection
Calls: VF.train.user -> trainDataCollect -> save
In addition: Warning message:
'rBind' is deprecated.
 Since R version 3.2.0, base's rbind() should work fine with S4 objects
Execution halted
`

What should I do ? 

Thanks,
Aly

**Comment by jessieren** [comment]
Hi @alyosama ,

Thank you very much for your interest in VirFinder. 

Could you please send me a sample of your training data so that I can debug on my computer?

Jessie

**Comment by alyosama** [comment]
Thanks @jessieren , I have fixed this issue on my machine. 

Anyways, I have realized that the training process is very very slow ( it took days). do you have any suggestions to make it faster ?

**Comment by jessieren** [comment]
Hi Aly,

I am sorry for my slow response!

The training process includes first fragment the input genomes into short contigs and counts kmers, and after processing contigs, it subsamples the same number of contigs for positive and negative, and trains a machine learning model based on the kmer frequencies.

The training can be slow if the size of your negative sequences (for example bacteria) is much larger than the size of the positive sequences. I would suggest reducing the size of the negative genome by downsampling a subset of the sequences and then use that as the input. In this way, it would not waste time processing all the sequences in the negative set and later only samples a few of them to match the number of positive sequences. Does that make sense? Or maybe this is not your situation?

Thanks!

Best wishes,
Jessie

________________________________________
