### ISSUE TITLE
‘virFinder’ is not available (for R version 3.5.2)

### ISSUE THREAD

**Issue by shafi-OZ** [jessieren/VirFinder#12]
Hi Jessieren
I use R 3.5.2 "Eggshell Igloo". I am trying to install virfinder but it gives me the following warning

install.packages("virfinder")
Warning in install.packages :
package ‘virfinder’ is not available (for R version 3.5.2)

Can you help with that, please?
Cheers

**Comment by jessieren** [comment]
Hi shafi-OZ,

Did you solve the problem? VirFinder is not on CRAN, so you have to install it by downloading the package and feed the path of the patch to the following command:

install.packages("<path_to_the_file>/VirFinder_1.1.tar.gz", repos = NULL, type="source") 

Hope it helps!

Jessie
