### ISSUE TITLE
The R Version with different internals

### ISSUE THREAD

**Issue by 25280841** [jessieren/VirFinder#14]
here I‘am using R3.5.3
while loading the VirFinder，there’s an error below：
 
package or namespace load failed for ‘VirFinder’:
 package ‘VirFinder’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version

**Comment by dbrandt91** [comment]
Same issue here. Reinstalling does not solve the problem.
I am using RStudio on Windows. 
Any ideas?

**Comment by jessieren** [comment]
Hi there, I tested in R 3.6 on Mac OS. I am able to install it. I am not sure if I can reproduce your error on my end. Thanks!

**Comment by DeaconOfBiology** [comment]
I am having the same issue with VirFinder 1.1 for windows.... any solutions? Running R 3.6

**Comment by jessieren** [comment]
Hi there, 

Can you download this package https://github.com/jessieren/VirFinder/blob/master/windows/R3.6/VirFinder_1.1.zip
and try to install it?

Thank you!

Jie

**Comment by dbrandt91** [comment]
Works for me. Thanks!

**Comment by DeaconOfBiology** [comment]
Works great!
________________________________
