### ISSUE TITLE
R package issue

### ISSUE THREAD

**Issue by DeaconOfBiology** [jessieren/VirFinder#17]
Hi,

I am trying to install the VirFinder package, but I am getting the following error:

package or namespace load failed for ‘VirFinder’:
package ‘VirFinder’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version

I am currently running Rstudio 3.64 on windows. Any advice?

**Comment by jessieren** [comment]
Hi there, 

Can you download this package https://github.com/jessieren/VirFinder/blob/master/windows/R3.6/VirFinder_1.1.zip
and try to install it again?

Thank you!

Jie

**Comment by DeaconOfBiology** [comment]
That worked perfectly! Thank you!
