### ISSUE TITLE
training by adding to the existing database

### ISSUE THREAD

**Issue by lalalagartija** [jessieren/VirFinder#22]
Hi ! 
Thank you for this tool. I wonder if it is possible to train virfinder by just adding to the existing database so I don't need to create everything from scratch.
Thank you in advance, 
Sofia

**Comment by jessieren** [comment]
Hi Sofia,

Thanks for your interest in our tool. The current version does not have the feature for adaptive learning. You have to train the model from scratch. 

Best regards,
Jie
