### ISSUE TITLE
Command line usage?

### ISSUE THREAD

**Issue by jolespin** [jessieren/VirFinder#26]
I'd like to add VirFinder into some command line pipelines.  Is it possible to run this from the command line instead of in R?

**Comment by jessieren** [comment]
Yes, you can write a script and run it from command line using Rscript. See here https://support.rstudio.com/hc/en-us/articles/218012917-How-to-run-R-scripts-from-the-command-line

**Comment by jolespin** [comment]
Do you have any command line executables that wrap the pipeline together with the parameters defaulted and predefined?

Something like:

run_virfinder -i input.fasta -o output.fasta

**Comment by jolespin** [comment]
Finding one right here!  
https://github.com/jessieren/VirFinder/blob/master/bin/VirFinder_wrapper.R. 
Awesome
