### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kali1819** [jessieren/VirFinder#9]
Hi, 

I am trying to install VirFinder on Windows but I have an error when executing Library(VirFinder)

Error: package or namespace load failed for ‘VirFinder’:
 package ‘VirFinder’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version

Can you help me with that?

**Comment by jessieren** [comment]
Hi Kali,

Thank you for your interest in VirFinder.

Based on the message so far I could not figure out the problem. Could you please install the package again and show me the message for the installation?

Besides, what R version you are using?

Thank you.

Jie

________________________________________

**Comment by jessieren** [comment]
I am closing the issue for now, but please feel free to reopen it if you still have questions.

**Comment by hahahehehuhuhei** [comment]
Hi jessieren,
I am trying to install VirFinder on Windows and I have the same problem as Kali---- error when executing Library(VirFinder) which shows:

Error: package or namespace load failed for ‘VirFinder’:
package ‘VirFinder’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version

btw I am using R version 3.5.2
Can you help me with that?
Best wishes.

**Comment by shafi-OZ** [comment]
Hi Jessieren 
I use R 3.5.2 "Eggshell Igloo". I am trying to install virfinder but it gives me the following warning 

install.packages("virfinder")
Warning in install.packages :
  package ‘virfinder’ is not available (for R version 3.5.2)

Can you help with that, please? 
Cheers

**Comment by pengouy** [comment]
Hi Jessieren,
I have successfully unpackaged "VirFinder" in R4.0.2 by RStudio1.3.959. But now I had some problems in loading package"VirFinder", it said like this in RStudio:
---------------------------------------------------------------------------------------------------------------------------
> install.packages("C:/Users/504/Desktop/VirFinder_1.1.zip", repos = NULL, type="source")
  Installing package into ‘C:/Users/504/Documents/R/win-library/4.0’
 (as ‘lib’ is unspecified)
   **package ‘VirFinder’ successfully unpacked and MD5 sums checked**
>  library(VirFinder)
   **error: package or namespace load failed for ‘VirFinder’:
   package ‘VirFinder’ was installed before R 4.0.0: please re-install it**
----------------------------------------------------------------------------------------------------------------------------

I also re-installed it several times after I updated R and RStudio, it still didn't work in right way. Could you please help me with this? Thank you!

**Comment by pengouy** [comment]
> ## Hi Jessieren,
> I have successfully unpackaged "VirFinder" in R4.0.2 by RStudio1.3.959. But now I had some problems in loading package"VirFinder", it said like this in RStudio:
> > install.packages("C:/Users/504/Desktop/VirFinder_1.1.zip", repos = NULL, type="source")
> > Installing package into ‘C:/Users/504/Documents/R/win-library/4.0’
> > (as ‘lib’ is unspecified)
> > **package ‘VirFinder’ successfully unpacked and MD5 sums checked**
> > library(VirFinder)
> > **error: package or namespace load failed for ‘VirFinder’:
> > package ‘VirFinder’ was installed before R 4.0.0: please re-install it**
> 
> I also re-installed it several times after I updated R and RStudio, it still didn't work in right way. Could you please help me with this? Thank you!

I've solved this problem by installing package for linux. BTW, I use windows.

**Comment by jessieren** [comment]
Hi Pengouy,

Glad to know that you finally installed the package. Sorry for the trouble, and thanks for reporting that. I do not have a good idea on why your windows operation systems installed the linux version successfully. I will take a look.

Thanks!
